# Generated by Django 4.2.5 on 2023-09-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('block_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.block')),
                ('name_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.name')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='name_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.name'),
        ),
    ]
