# Generated by Django 4.2.5 on 2023-09-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('IN', 'India'), ('BR', 'Brazil'), ('MX', 'Mexico'), ('AR', 'Argentina'), ('ZA', 'South Africa'), ('NG', 'Nigeria'), ('SA', 'Saudi Arabia'), ('PK', 'Pakistan')], max_length=100),
        ),
    ]
